name: aad
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pip:
      - -e common/
      - torch
      - torchvision
      - piq